###
GET http://localhost:8080/api/orders/find-all

###
POST http://localhost:8080/api/orders/save
Content-Type: application/json

{
    "name": "customer Name",
    "phone": "0962122004",
    "email": "hoangaphu69@gmail.com",
    "address": "VJ4J+524, Tân Hưng Thuận, Quận 12, Thành phố Hồ Chí Minh",
    "deliveryDate": "2024-04-09 18:09:46.256+07",
    "orderDate": "2024-04-09 18:09:46.256+07",
    "quantity": 12,
    "brand": "bullball",
    "deposit": 500000,
    "totalPrice": 1250000,
    "currency": "VND",
    "noteByCustomer": "Sống giàu có hơn ngay từ hôm nay ",
    "note": "Chúng tôi luôn luôn cập nhật những ưu đãi hấp dẫn nhất!",
    "status": "2",
    "orderBy": "Hoàng Phú",
    "tax": 10,
    "createdBy": "admin",
    "updatedBy": "admin"
}

###
PUT http://localhost:8080/api/orders/update
Content-Type: application/json

{
    "id": 1,
    "name": "customer Name edit",
    "phone": "0962122004",
    "email": "hoangaphu69@gmail.com",
    "address": "VJ4J+524, Tân Hưng Thuận, Quận 12, Thành phố Hồ Chí Minh",
    "deliveryDate": "2024-04-05 18:09:46.256+07",
    "orderDate": "2024-04-05 18:09:46.256+07",
    "quantity": 12,
    "brand": "bullball",
    "deposit": 500000,
    "totalPrice": 1250000,
    "currency": "VND",
    "noteByCustomer": "Sống giàu có hơn ngay từ hôm nay ",
    "note": "Chúng tôi luôn luôn cập nhật những ưu đãi hấp dẫn nhất!",
    "status": "2",
    "orderBy": "Hoàng Phú",
    "tax": 10,
    "createdBy": "admin",
    "updatedBy": "admin"
}

###
GET http://localhost:8080/api/orders/find-by-id/2

###
DELETE http://localhost:8080/api/orders/delete-by-id/2

